name: Accessibility

on:
  pull_request:
    branches:
      - main
      - next
    paths:
      - '.github/workflows/accessibility.yml'
      - 'package.json'
      - 'playwright.config.*'
      - 'svelte.config.*'
      - 'vite.config.*'
      - 'wrangler.jsonc'
      - 'pnpm-lock.yaml'
      - 'src/**'
      - 'static/**'
      - 'tests/**'
  push:
    branches:
      - main
      - next
    paths:
      - '.github/workflows/accessibility.yml'
      - 'package.json'
      - 'playwright.config.*'
      - 'svelte.config.*'
      - 'vite.config.*'
      - 'wrangler.jsonc'
      - 'pnpm-lock.yaml'
      - 'src/**'
      - 'static/**'
      - 'tests/**'
  workflow_dispatch:
permissions:
  contents: read
env:
  FORCE_COLOR: 1

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up PNPM
        uses: pnpm/setup@84cb39b217b10273981911c288cd62326dc7c6d2 # v2.0.2
        with:
          version: 11
          cache: true
          runtime: node@lts

      - name: Run Accessibility Audit
        run: pnpm run test:ci
